# Action 名稱
name: Deploy
# 觸發時機
on:
  push:
# 當推送到分支 master 時
    branches: [ master ]
# 每隔 10 分鐘時
  schedule:
    - cron: "*/10 0 * * *"
# 執行的工作
jobs:
  # 工作名稱
  deploy:
    # 執行工作的虛擬機作業系統
    runs-on: ubuntu-latest
    # 工作步驟
    steps:
      # 步驟一：複製程式碼 (固定)
      - name: checkout
        # 使用的 actions/checkout 複製程式碼
        uses: actions/checkout@v3
      # 步驟二：編譯
      - name: Install and dev
        run: |
          npm install
      # 步驟三：部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          floder: .
